name: build

on:
  push:
  pull_request:
  schedule:
    - cron: 0 1 * * 1
  workflow_dispatch:


jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Run fmt
        run: cargo fmt --all -- --check

  audit:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit Rust Dependencies
        uses: actions-rust-lang/audit@v1


  build:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    needs:
      - fmt
      - audit

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            toolchain: stable
            os: ubuntu-latest
            features: git

          - target: x86_64-apple-darwin
            toolchain: stable
            os: macos-latest
            features: git

          - target: x86_64-pc-windows-msvc
            toolchain: stable
            os: windows-latest
            features: git

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run build
        run: cargo build --target ${{ matrix.target }} --features ${{ matrix.features }} --no-default-features --workspace

      - name: Run clippy
        run: cargo clippy --target ${{ matrix.target }} --features ${{ matrix.features }} --no-default-features --workspace -- -D warnings

      - name: Run tests
        run: cargo nextest run --target ${{ matrix.target }} --features ${{ matrix.features }} --workspace

      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-test-results
          path: target/nextest/**/*.xml

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report (${{ matrix.target }})
          path: target/nextest/**/*.xml
          reporter: java-junit

      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results (${{ matrix.target }})
          path: target/nextest/**/*.xml

  test-results:
    runs-on: ubuntu-latest
    needs: build
    if: success() || failure()

    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/*.xml"

  doc:
    runs-on: ubuntu-latest
    needs: build

    env:
      MDBOOK_VERSION: 0.4.36

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Install mdBook
        run: cargo install --version ${MDBOOK_VERSION} mdbook

      - name: Make the doc
        run: make doc

      - name: Make the book
        run: make book

      - name: Deploy the doc
        uses: actions/upload-artifact@v4
        with:
          name: doc
          path: target/doc

      - name: Deploy the book
        uses: actions/upload-artifact@v4
        with:
          name: book
          path: doc/book

      - name: Deploy GitHub pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/book


  github-pages:
    runs-on: ubuntu-latest
    needs: doc
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
